version: '3'

services:
  db:
    build:
      context: ../
      dockerfile: docker/db.dockerfile
    image: cyclo-db
    container_name: cyclo-db
    volumes:
      - ./tmp/db:/var/lib/postgresql-static/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: cyclo
    ports:
      - '54322:5432'

  redis_cluster:
    image: redis:6.2.6
    container_name: cyclo-redis
    ports:
      - "6379:6379"


