output   = "internal/models"
pkgname = "models"
wipe     = true
no-tests = true

[psql]
  dbname = "cyclo"
  host   = "localhost"
  port   = 54322
  user   = "postgres"
  pass   = "postgres"
  schema = "cyclo"
  blacklist = ["migrations", "other"]
  sslmode = "disable"
